"""NSPasteboard wrapper for reading HTML + text from macOS clipboard.

Why not pyperclip? Because Excel puts both HTML and TSV on the clipboard,
and pyperclip only sees the text portion. We need NSPasteboard to read HTML.
"""
from AppKit import NSPasteboard, NSPasteboardTypeHTML, NSPasteboardTypeString

LEGACY_HTML_TYPE = "Apple HTML pasteboard type"
LEGACY_STRING_TYPE = "NSStringPboardType"
HTML_TYPES = {str(NSPasteboardTypeHTML), LEGACY_HTML_TYPE}
STRING_TYPES = {str(NSPasteboardTypeString), LEGACY_STRING_TYPE}
AUTO_GENERATED_TYPE = "org.nspasteboard.AutoGeneratedType"
TABLEDOWN_GENERATED_TYPE = "com.tabledown.generated"
GENERATED_MARKER_TYPES = {
    AUTO_GENERATED_TYPE: "Tabledown",
    TABLEDOWN_GENERATED_TYPE: "Tabledown",
}
RENDERED_TABLE_TYPES = {
    "public.png",
    "Apple PNG pasteboard type",
    "public.tiff",
    "NeXT TIFF v4.0 pasteboard type",
    "com.adobe.pdf",
    "Apple PDF pasteboard type",
    "public.rtf",
    "NeXT Rich Text Format v1.0 pasteboard type",
    "com.apple.webarchive",
    "Apple Web Archive pasteboard type",
}


def clipboard_change_count() -> int:
    """Return the current clipboard change counter."""
    return int(NSPasteboard.generalPasteboard().changeCount())


def read_clipboard() -> dict:
    """Read both HTML and plain text from clipboard.

    Returns:
        dict with optional 'html', 'text', and 'generated' keys.
    """
    pb = NSPasteboard.generalPasteboard()
    result = {}

    if has_generated_marker(pb):
        result["generated"] = True

    html = pb.stringForType_(NSPasteboardTypeHTML)
    if html:
        result["html"] = str(html)

    text = pb.stringForType_(NSPasteboardTypeString)
    if text:
        result["text"] = str(text)

    return result


def has_generated_marker(pb=None) -> bool:
    """Return True when the current clipboard was generated by Tabledown."""
    if pb is None:
        pb = NSPasteboard.generalPasteboard()
    for pb_type, expected_value in GENERATED_MARKER_TYPES.items():
        value = pb.stringForType_(pb_type)
        if value and str(value) == expected_value:
            return True
    return False


def write_clipboard(
    text: str | None = None,
    html: str | None = None,
    mark_generated: bool = False,
    drop_types: set[str] | None = None,
) -> None:
    """Update text/html formats while preserving existing clipboard formats."""
    pb = NSPasteboard.generalPasteboard()
    drop_types = drop_types or set()
    existing_data = {}
    for pb_type in pb.types() or []:
        pb_type = str(pb_type)
        if pb_type in drop_types:
            continue
        data = pb.dataForType_(pb_type)
        if data is not None:
            existing_data[pb_type] = data

    replaced_types = set()
    if text is not None:
        replaced_types.update(STRING_TYPES)
    if html is not None:
        replaced_types.update(HTML_TYPES)

    marker_types = set(GENERATED_MARKER_TYPES) if mark_generated else set()

    declared_types = []
    for pb_type in existing_data:
        if pb_type not in declared_types:
            declared_types.append(pb_type)
    for pb_type in [str(NSPasteboardTypeString), LEGACY_STRING_TYPE]:
        if text is not None and pb_type not in declared_types:
            declared_types.append(pb_type)
    for pb_type in [str(NSPasteboardTypeHTML), LEGACY_HTML_TYPE]:
        if html is not None and pb_type not in declared_types:
            declared_types.append(pb_type)
    for pb_type in marker_types:
        if pb_type not in declared_types:
            declared_types.append(pb_type)

    pb.clearContents()
    pb.declareTypes_owner_(declared_types, None)

    for pb_type, data in existing_data.items():
        if pb_type not in replaced_types and pb_type not in marker_types:
            pb.setData_forType_(data, pb_type)
    if text is not None:
        for pb_type in STRING_TYPES:
            pb.setString_forType_(text, pb_type)
    if html is not None:
        for pb_type in HTML_TYPES:
            pb.setString_forType_(html, pb_type)
    if mark_generated:
        for pb_type, value in GENERATED_MARKER_TYPES.items():
            pb.setString_forType_(value, pb_type)
