"""NSPasteboard wrapper for reading HTML + text from macOS clipboard.

Why not pyperclip? Because Excel puts both HTML and TSV on the clipboard,
and pyperclip only sees the text portion. We need NSPasteboard to read HTML.
"""
from AppKit import NSPasteboard, NSPasteboardTypeHTML, NSPasteboardTypeString

LEGACY_HTML_TYPE = "Apple HTML pasteboard type"
LEGACY_STRING_TYPE = "NSStringPboardType"
HTML_TYPES = {str(NSPasteboardTypeHTML), LEGACY_HTML_TYPE}
STRING_TYPES = {str(NSPasteboardTypeString), LEGACY_STRING_TYPE}
AUTO_GENERATED_TYPE = "org.nspasteboard.AutoGeneratedType"
TABLEDOWN_GENERATED_TYPE = "com.tabledown.generated"
GENERATED_MARKER_TYPES = {
    AUTO_GENERATED_TYPE: "Tabledown",
    TABLEDOWN_GENERATED_TYPE: "Tabledown",
}
RENDERED_TABLE_TYPES = {
    "public.png",
    "Apple PNG pasteboard type",
    "public.tiff",
    "NeXT TIFF v4.0 pasteboard type",
    "com.adobe.pdf",
    "Apple PDF pasteboard type",
    "public.rtf",
    "NeXT Rich Text Format v1.0 pasteboard type",
    "com.apple.webarchive",
    "Apple Web Archive pasteboard type",
}


class ClipboardChangedError(RuntimeError):
    """The clipboard changed after an explicit export started."""


class ClipboardWriteError(OSError):
    """A text-only clipboard export could not be verified."""


def clipboard_change_count() -> int:
    """Return the current clipboard change counter."""
    return int(NSPasteboard.generalPasteboard().changeCount())


def read_clipboard() -> dict:
    """Read both HTML and plain text from clipboard.

    Returns:
        dict with optional 'html', 'text', and 'generated' keys.
    """
    pb = NSPasteboard.generalPasteboard()
    result = {}

    if has_generated_marker(pb):
        result["generated"] = True

    html = pb.stringForType_(NSPasteboardTypeHTML)
    if html:
        result["html"] = str(html)

    text = pb.stringForType_(NSPasteboardTypeString)
    if text:
        result["text"] = str(text)

    return result


def has_generated_marker(pb=None) -> bool:
    """Return True when the current clipboard was generated by Tabledown."""
    if pb is None:
        pb = NSPasteboard.generalPasteboard()
    for pb_type, expected_value in GENERATED_MARKER_TYPES.items():
        value = pb.stringForType_(pb_type)
        if value and str(value) == expected_value:
            return True
    return False


def write_clipboard(
    text: str | None = None,
    html: str | None = None,
    mark_generated: bool = False,
    drop_types: set[str] | None = None,
    *,
    expected_change_count: int | None = None,
) -> None:
    """Update formats only while the watcher still owns the source generation.

    NSPasteboard has no atomic compare-and-swap.  Checking both before reading
    preserved formats and immediately before ``clearContents`` narrows the
    unavoidable check→clear window and prevents an older conversion from
    normally being mixed into a newer external copy.
    """
    pb = NSPasteboard.generalPasteboard()
    if (
        expected_change_count is not None
        and int(pb.changeCount()) != expected_change_count
    ):
        raise ClipboardChangedError("clipboard_changed")
    drop_types = drop_types or set()
    existing_data = {}
    for pb_type in pb.types() or []:
        pb_type = str(pb_type)
        if pb_type in drop_types:
            continue
        data = pb.dataForType_(pb_type)
        if data is not None:
            existing_data[pb_type] = data

    replaced_types = set()
    if text is not None:
        replaced_types.update(STRING_TYPES)
    if html is not None:
        replaced_types.update(HTML_TYPES)

    marker_types = set(GENERATED_MARKER_TYPES) if mark_generated else set()

    declared_types = []
    for pb_type in existing_data:
        if pb_type not in declared_types:
            declared_types.append(pb_type)
    for pb_type in [str(NSPasteboardTypeString), LEGACY_STRING_TYPE]:
        if text is not None and pb_type not in declared_types:
            declared_types.append(pb_type)
    for pb_type in [str(NSPasteboardTypeHTML), LEGACY_HTML_TYPE]:
        if html is not None and pb_type not in declared_types:
            declared_types.append(pb_type)
    for pb_type in marker_types:
        if pb_type not in declared_types:
            declared_types.append(pb_type)

    if (
        expected_change_count is not None
        and int(pb.changeCount()) != expected_change_count
    ):
        raise ClipboardChangedError("clipboard_changed")
    pb.clearContents()
    pb.declareTypes_owner_(declared_types, None)

    for pb_type, data in existing_data.items():
        if pb_type not in replaced_types and pb_type not in marker_types:
            pb.setData_forType_(data, pb_type)
    if text is not None:
        for pb_type in STRING_TYPES:
            pb.setString_forType_(text, pb_type)
    if html is not None:
        for pb_type in HTML_TYPES:
            pb.setString_forType_(html, pb_type)
    if mark_generated:
        for pb_type, value in GENERATED_MARKER_TYPES.items():
            pb.setString_forType_(value, pb_type)


def write_table_clipboard(
    text: str,
    html: str,
    mark_generated: bool = True,
    *,
    expected_change_count: int | None = None,
) -> None:
    """Replace an explicit selection export with verified text and HTML only.

    Both formats describe the same Excel snapshot. Old native, image, and rich
    text formats are discarded so a destination cannot paste an older copy.
    The final generation check immediately precedes clearing the pasteboard,
    but macOS offers no atomic compare-and-swap for that check and clear.
    A failure after clearing is reported without retrying or restoring old
    contents, because another app may already own newer clipboard content.
    """
    try:
        pb = NSPasteboard.generalPasteboard()
        if (
            expected_change_count is not None
            and int(pb.changeCount()) != expected_change_count
        ):
            raise ClipboardChangedError("clipboard_changed")

        values = [
            (str(NSPasteboardTypeString), text),
            (LEGACY_STRING_TYPE, text),
            (str(NSPasteboardTypeHTML), html),
            (LEGACY_HTML_TYPE, html),
        ]
        if mark_generated:
            values.extend(GENERATED_MARKER_TYPES.items())
        declared_types = [pb_type for pb_type, _ in values]

        if (
            expected_change_count is not None
            and int(pb.changeCount()) != expected_change_count
        ):
            raise ClipboardChangedError("clipboard_changed")
        pb.clearContents()
        pb.declareTypes_owner_(declared_types, None)
        for pb_type, value in values:
            if pb.setString_forType_(value, pb_type) is False:
                raise ClipboardWriteError("clipboard_write_failed")
        for pb_type, expected in values:
            actual = pb.stringForType_(pb_type)
            if actual is None or str(actual) != expected:
                raise ClipboardWriteError("clipboard_write_failed")
    except Exception as exc:
        if isinstance(exc, (ClipboardChangedError, ClipboardWriteError)):
            raise
        raise ClipboardWriteError("clipboard_write_failed") from None


def write_text_only_clipboard(
    text: str,
    mark_generated: bool = True,
    *,
    expected_change_count: int | None = None,
) -> None:
    """Replace the clipboard with plain text and Tabledown's marker only.

    Unlike :func:`write_clipboard`, this intentionally preserves no native,
    HTML, image, or rich-text formats.  It is reserved for explicit exports
    where the requested result is text, and is never used by the watcher.

    ``expected_change_count`` prevents a slow Excel read from overwriting
    something the user copied while the export was running.  Success is only
    returned after every declared text/marker value reads back exactly.  The OS
    pasteboard is not transactional; after ``clearContents`` a failed write is
    reported but never "rolled back", because another app may already own newer
    clipboard content by then.
    """
    pb = NSPasteboard.generalPasteboard()
    if (
        expected_change_count is not None
        and int(pb.changeCount()) != expected_change_count
    ):
        raise ClipboardChangedError("clipboard_changed")

    text_types = [str(NSPasteboardTypeString), LEGACY_STRING_TYPE]
    marker_types = list(GENERATED_MARKER_TYPES) if mark_generated else []

    try:
        pb.clearContents()
        pb.declareTypes_owner_(text_types + marker_types, None)
        for pb_type in text_types:
            if pb.setString_forType_(text, pb_type) is False:
                raise ClipboardWriteError("clipboard_write_failed")
        if mark_generated:
            for pb_type, value in GENERATED_MARKER_TYPES.items():
                if pb.setString_forType_(value, pb_type) is False:
                    raise ClipboardWriteError("clipboard_write_failed")

        for pb_type in text_types:
            actual = pb.stringForType_(pb_type)
            if actual is None or str(actual) != text:
                raise ClipboardWriteError("clipboard_write_failed")
        if mark_generated:
            for pb_type, expected in GENERATED_MARKER_TYPES.items():
                actual = pb.stringForType_(pb_type)
                if actual is None or str(actual) != expected:
                    raise ClipboardWriteError("clipboard_write_failed")
    except Exception as exc:
        if isinstance(exc, ClipboardWriteError):
            raise
        raise ClipboardWriteError("clipboard_write_failed") from None
