"""Windows clipboard wrapper for text and HTML table formats."""
from __future__ import annotations

from contextlib import contextmanager
import ctypes
import time
from typing import Iterable

import pywintypes
import win32clipboard
import win32con

from .html_clipboard import CF_HTML_FORMAT_NAME, build_cf_html, extract_cf_html


TABLEDOWN_GENERATED_TYPE = "com.tabledown.generated"
GENERATED_MARKER_VALUE = "Tabledown"

HTML_FORMAT_ID = win32clipboard.RegisterClipboardFormat(CF_HTML_FORMAT_NAME)
GENERATED_FORMAT_ID = win32clipboard.RegisterClipboardFormat(TABLEDOWN_GENERATED_TYPE)

TEXT_FORMATS = {
    win32con.CF_TEXT,
    win32con.CF_OEMTEXT,
    win32con.CF_UNICODETEXT,
}

BUILTIN_FORMAT_NAMES = {
    win32con.CF_BITMAP: "Bitmap",
    win32con.CF_DIB: "DeviceIndependentBitmap",
    win32con.CF_DIBV5: "DeviceIndependentBitmapV5",
    win32con.CF_ENHMETAFILE: "EnhancedMetafile",
    win32con.CF_METAFILEPICT: "MetafilePict",
    win32con.CF_UNICODETEXT: "Unicode Text",
}

DROP_FORMAT_NAME_TO_ID = {
    CF_HTML_FORMAT_NAME: HTML_FORMAT_ID,
    "Bitmap": win32con.CF_BITMAP,
    "DeviceIndependentBitmap": win32con.CF_DIB,
    "DeviceIndependentBitmapV5": win32con.CF_DIBV5,
    "EnhancedMetafile": win32con.CF_ENHMETAFILE,
    "MetafilePict": win32con.CF_METAFILEPICT,
}


def clipboard_change_count() -> int:
    """Return the current Windows clipboard sequence number."""
    return int(ctypes.windll.user32.GetClipboardSequenceNumber())


def read_clipboard() -> dict:
    """Read HTML and plain text from the Windows clipboard."""
    result = {}
    with _open_clipboard():
        if has_generated_marker(opened=True):
            result["generated"] = True

        if win32clipboard.IsClipboardFormatAvailable(HTML_FORMAT_ID):
            html_data = win32clipboard.GetClipboardData(HTML_FORMAT_ID)
            html = extract_cf_html(html_data)
            if html:
                result["html"] = html

        if win32clipboard.IsClipboardFormatAvailable(win32con.CF_UNICODETEXT):
            text = win32clipboard.GetClipboardData(win32con.CF_UNICODETEXT)
            if text:
                result["text"] = str(text)

    return result


def has_generated_marker(opened: bool = False) -> bool:
    """Return True when the current clipboard was generated by Tabledown."""
    if opened:
        return _has_generated_marker_opened()
    with _open_clipboard():
        return _has_generated_marker_opened()


def write_clipboard(
    text: str | None = None,
    html: str | None = None,
    mark_generated: bool = False,
    drop_formats: Iterable[str] | None = None,
) -> None:
    """Update text/html formats while preserving restorable clipboard formats."""
    drop_format_names = set(drop_formats or ())
    drop_format_ids = {DROP_FORMAT_NAME_TO_ID[name] for name in drop_format_names if name in DROP_FORMAT_NAME_TO_ID}

    replaced_format_ids = set()
    if text is not None:
        replaced_format_ids.update(TEXT_FORMATS)
    if html is not None:
        replaced_format_ids.add(HTML_FORMAT_ID)
    if mark_generated:
        replaced_format_ids.add(GENERATED_FORMAT_ID)

    with _open_clipboard():
        preserved = []
        for fmt in _enum_formats():
            if fmt in replaced_format_ids or fmt in drop_format_ids:
                continue
            if _format_name(fmt) in drop_format_names:
                continue
            try:
                data = win32clipboard.GetClipboardData(fmt)
            except (pywintypes.error, TypeError):
                continue
            if _can_restore_data(data):
                preserved.append((fmt, data))

        win32clipboard.EmptyClipboard()

        for fmt, data in preserved:
            try:
                win32clipboard.SetClipboardData(fmt, data)
            except (pywintypes.error, TypeError):
                continue

        if text is not None:
            win32clipboard.SetClipboardData(win32con.CF_UNICODETEXT, text)
        if html is not None:
            win32clipboard.SetClipboardData(HTML_FORMAT_ID, build_cf_html(html))
        if mark_generated:
            win32clipboard.SetClipboardData(GENERATED_FORMAT_ID, GENERATED_MARKER_VALUE.encode("utf-8"))


@contextmanager
def _open_clipboard():
    opened = False
    last_error = None
    for _ in range(20):
        try:
            win32clipboard.OpenClipboard(None)
            opened = True
            break
        except pywintypes.error as exc:
            last_error = exc
            time.sleep(0.03)
    if not opened:
        raise last_error or RuntimeError("Unable to open clipboard")
    try:
        yield
    finally:
        win32clipboard.CloseClipboard()


def _has_generated_marker_opened() -> bool:
    if not win32clipboard.IsClipboardFormatAvailable(GENERATED_FORMAT_ID):
        return False
    try:
        value = win32clipboard.GetClipboardData(GENERATED_FORMAT_ID)
    except (pywintypes.error, TypeError):
        return False
    return _decode_marker(value) == GENERATED_MARKER_VALUE


def _decode_marker(value) -> str:
    if isinstance(value, bytes):
        for encoding in ("utf-8", "utf-16"):
            try:
                return value.decode(encoding).rstrip("\0")
            except UnicodeDecodeError:
                continue
        return value.decode("utf-8", errors="replace").rstrip("\0")
    return str(value).rstrip("\0")


def _enum_formats() -> list[int]:
    formats = []
    fmt = 0
    while True:
        fmt = win32clipboard.EnumClipboardFormats(fmt)
        if fmt == 0:
            return formats
        formats.append(fmt)


def _format_name(fmt: int) -> str:
    if fmt in BUILTIN_FORMAT_NAMES:
        return BUILTIN_FORMAT_NAMES[fmt]
    try:
        return win32clipboard.GetClipboardFormatName(fmt)
    except pywintypes.error:
        return str(fmt)


def _can_restore_data(data) -> bool:
    return isinstance(data, (bytes, str))
